area:api:
  - changed-files:
    - any-glob-to-any-file: 'src/fu7ur3pr00f/api/**/*'
area:frontend:
  - app/**/*
area:infra:
  - .github/**/*
  - pyproject.toml
python:
  - "**/*.py"
documentation:
  - "**/*.md"