#!/usr/bin/env bash
set -euo pipefail

# FutureProof Setup Script
# Configures Azure OpenAI and copies career data automatically

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"
CONFIG_DIR="${HOME}/.fu7ur3pr00f"
DATA_DIR="${CONFIG_DIR}/data/raw"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

error() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >&2
}

# Check if az CLI is installed
if ! command -v az &> /dev/null; then
  error "Azure CLI not found. Install it first:"
  echo "  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"
  exit 1
fi

# Check if logged in to Azure
if ! az account show &> /dev/null; then
  log "Not logged in to Azure. Starting device code login..."
  az login --use-device-code
fi

log "Azure subscription: $(az account show --query name -o tsv)"

# Find Azure OpenAI resource
log "Searching for Azure OpenAI resources..."
RESOURCE_INFO=$(az cognitiveservices account list --query "[?kind=='OpenAI'] | [0]" -o json 2>/dev/null || echo "{}")

if [[ "${RESOURCE_INFO}" == "{}" || "${RESOURCE_INFO}" == "null" ]]; then
  error "No Azure OpenAI resource found in subscription"
  echo "Create one at: https://portal.azure.com/#create/Microsoft.CognitiveServicesOpenAI"
  exit 1
fi

RESOURCE_NAME=$(echo "${RESOURCE_INFO}" | jq -r '.name')
RESOURCE_GROUP=$(echo "${RESOURCE_INFO}" | jq -r '.resourceGroup')
ENDPOINT=$(echo "${RESOURCE_INFO}" | jq -r '.properties.endpoint')

log "Found Azure OpenAI resource: ${RESOURCE_NAME} (in ${RESOURCE_GROUP})"
log "Endpoint: ${ENDPOINT}"

# Get API key
log "Retrieving API key..."
API_KEY=$(az cognitiveservices account keys list \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${RESOURCE_NAME}" \
  --query key1 -o tsv)

# Get deployments
log "Listing deployments..."
DEPLOYMENTS=$(az cognitiveservices account deployment list \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${RESOURCE_NAME}" \
  --query "[].name" -o json)

# Pick default deployments
AGENT_MODEL=$(echo "${DEPLOYMENTS}" | jq -r '.[] | select(contains("gpt-4.1-mini") or contains("gpt-4o-mini"))' | head -n1)
ANALYSIS_MODEL=$(echo "${DEPLOYMENTS}" | jq -r '.[] | select(contains("gpt-4o") and (contains("mini") | not))' | head -n1)
EMBEDDING_MODEL=$(echo "${DEPLOYMENTS}" | jq -r '.[] | select(contains("embedding"))' | head -n1)

# Fallbacks if specific models not found
AGENT_MODEL=${AGENT_MODEL:-$(echo "${DEPLOYMENTS}" | jq -r '.[0]')}
ANALYSIS_MODEL=${ANALYSIS_MODEL:-${AGENT_MODEL}}
EMBEDDING_MODEL=${EMBEDDING_MODEL:-"text-embedding-3-small"}

log "Selected deployments:"
log "  Agent: ${AGENT_MODEL}"
log "  Analysis: ${ANALYSIS_MODEL}"
log "  Embedding: ${EMBEDDING_MODEL}"

# Create config directory
mkdir -p "${CONFIG_DIR}"
chmod 700 "${CONFIG_DIR}"

# Write .env file
ENV_FILE="${CONFIG_DIR}/.env"
log "Writing configuration to ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Azure OpenAI Configuration
# Auto-generated by $(basename "${BASH_SOURCE[0]}") on $(date -Iseconds)

AZURE_OPENAI_API_KEY=${API_KEY}
AZURE_OPENAI_ENDPOINT=${ENDPOINT%/}
AZURE_OPENAI_API_VERSION=2024-12-01-preview

# Deployments
AZURE_CHAT_DEPLOYMENT=${AGENT_MODEL}
AZURE_EMBEDDING_DEPLOYMENT=${EMBEDDING_MODEL}

# Purpose-based routing
AGENT_MODEL=${AGENT_MODEL}
ANALYSIS_MODEL=${ANALYSIS_MODEL}
SUMMARY_MODEL=${AGENT_MODEL}
SYNTHESIS_MODEL=${ANALYSIS_MODEL}
EMBEDDING_MODEL=${EMBEDDING_MODEL}
EOF

chmod 600 "${ENV_FILE}"
log "Configuration saved (permissions: 0600)"

# Copy career data if it exists in project
PROJECT_DATA="${PROJECT_ROOT}/data/raw"
if [[ -d "${PROJECT_DATA}" ]] && [[ "$(ls -A "${PROJECT_DATA}" 2>/dev/null | grep -v '^\.gitkeep$')" ]]; then
  log "Copying career data from project to ${DATA_DIR}..."
  mkdir -p "${DATA_DIR}"
  chmod 700 "${DATA_DIR}"
  
  # Copy files (excluding .gitkeep)
  find "${PROJECT_DATA}" -type f ! -name '.gitkeep' -exec cp {} "${DATA_DIR}/" \;
  
  COPIED=$(ls -1 "${DATA_DIR}" | wc -l)
  log "Copied ${COPIED} file(s) to ${DATA_DIR}"
else
  log "No career data found in ${PROJECT_DATA}"
  log "Add your files there and run this script again, or place them in ${DATA_DIR}"
fi

# Test connection
log "Testing Azure OpenAI connection..."
TEST_RESPONSE=$(curl -s -X POST "${ENDPOINT}/openai/deployments/${AGENT_MODEL}/chat/completions?api-version=2024-12-01-preview" \
  -H "Content-Type: application/json" \
  -H "api-key: ${API_KEY}" \
  -d '{"messages":[{"role":"user","content":"Hi"}],"max_tokens":5}')

if echo "${TEST_RESPONSE}" | jq -e '.choices' &> /dev/null; then
  log "✓ Azure OpenAI connection successful!"
else
  error "Failed to connect to Azure OpenAI"
  echo "Response: ${TEST_RESPONSE}"
  exit 1
fi

echo ""
echo "=============================================="
echo "✓ Setup complete!"
echo "=============================================="
echo ""
echo "Configuration: ${ENV_FILE}"
echo "Data directory: ${DATA_DIR}"
echo ""
echo "Start the chat with:"
echo "  fu7ur3pr00f"
echo ""
